export { default as Home } from './Home';
export { default as HomeEng } from './HomeEng';
export { default as Actor } from './Actor';
export { default as Dancer } from './Dancer';
export { default as Biography } from './Biography';
export { default as Showreel } from './Showreel';
export { default as Contact } from './Contact';
export { default as Commercially } from './commercially';
export { default as CV } from './CV';
